application: inimailbot
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: media/img/favicon.ico
  upload: media/img/favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /css
  static_dir: css

- url: /_ah/mail/ankidroid_crash_reports@inimailbot\.appspotmail\.com.*
  script: receive_ankicrashes.py

- url: /ankidroid_triage/admin_.*
  script: admin_ops.py
  login: admin

- url: /ankidroid_triage.*
  script: report_ankicrashes.py

inbound_services:
- mail

