application: inimailbot
version: 1
runtime: python
api_version: 1

handlers:
- url: /_ah/mail/ankidroid_crash_reports@inimailbot\.appspotmail\.com.*
  script: receive_ankicrashes.py

- url: /ankidroid_triage.*
  script: report_ankicrashes.py

- url: /css
  static_dir: css

inbound_services:
- mail

